name: publish-tf-index
on:
  push:
    branches: [ archive-full-index ]
    paths: 'bitnami/index.yaml'
  workflow_dispatch:
jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: archive-full-index
        path: main
    - name: Checkout gh-pages repo
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    - name: Copy the index
      run: |
        find ./main/bitnami/ -type f -name "index.yaml" | while read fname; do
          dirname=`dirname "$fname"`
          foldername=`basename "$dirname"`
          filename=`basename "$fname"`
          newname=`echo "$dirname" | sed -e "s/ /_/g"`
          cp "${dirname}/$filename" "./gh-pages/bitnami/index.yaml"
        done
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "repository: https://charts.bitnami.com/bitnami"
        replace: "repository: https://bitnami.techfreak.ch/bitnami"
        include: "gh-pages/bitnami/index.yaml"
    - name: Commit files
      run: |
        cd ./gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        directory: ./gh-pages
